<!DOCTYPE html>
<html lang="en"><!-- InstanceBegin template="/Templates/subpage.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
<!-- InstanceBeginEditable name="meta" -->
<!-- InstanceEndEditable -->
<!--[if gte IE 9]><meta http-equiv="X-UA-Compatible" content="IE=Edge"><![endif]-->
<!-- InstanceBeginEditable name="doctitle" -->
<title>Chapman University</title>
<!-- InstanceEndEditable -->
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="../css/harv.css">
<link rel="stylesheet" type="text/css" href="../css/harvdrop.css">
<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><script src="/js/html5shiv.js"></script><![endif]-->
<script src='http://code.jquery.com/jquery-latest.min.js' type='text/javascript'></script><script src="/js/jquery.ui.totop.js"></script>
<!-- InstanceBeginEditable name="head" --><style>
.text_box, p {
	text-align: left !important;
}
#middle #mainsub .biblio-abstract-link.toggle {
}
</style>
<!-- InstanceEndEditable -->
</head>
<body>
<div id="container">
  <div id="smNavBk"><a href="http://compbiosciences.chapman.edu/index.php"><img src="../images/header400light.png" width="332" height="58" alt="Chapman University" style="float: left; margin-left: 10px; margin-top: 10px;"></a>
    <div id="collegeLinks" style="font-size: 24px;">
      <p><a href="https://www.chapman.edu/scst/"><strong><img src="../images/xdz1wyqhwtmxxekidsyy.jpg" width="35" height="35" alt=""/>Schmid College of Science and Technology</strong></a></p>
      <p><a href="http://www.chapman.edu/"><img src="../images/open-graph-cu-logo.png" alt="Chapman University" width="35" height="30" title="Chapman University"/> <span style="font-style: normal; font-size: 18pt;">Chapman University</span></a></p>
    </div>
    <div class="clear"></div>
  </div>
  </header>
  <nav id="topMenu" class="desktop"><!-- #BeginLibraryItem "/Library/topMenu.lbi" --> <nav id="topMenu" class="desktop"><ul id="TopNav" class="MenuBarHorizontal">
      <li> <a href="../index.php">Home</a></li>
      <li><a href="../members.php">Members</a>          
  <li><a href="../Research/research.php" class="MenuBarItemSubmenu">Research</a>
        <ul>
          <li><a href="../Research/computationalCancerBiology.php" >Computational Biology and Translational Bioinformatics in Cancer Research</a></li>
          <li><a href="../Research/proteinKinasesResearch.php" >Protein Kinases</a></li>
          <li><a href="../Research/molecularChaperonesAndCancerResearch.php">Computatoinal Studies of Molecular Chaperones</a></li>
          <li><a href="../Research/translationalBioinformatics.php" >Translational Bioinformatics and Drug Discovery</a></li>
          <li><a href="../Research/relatedResearch.php">Related Links</a></li>
        </ul>
  </li>
      <li><a href="publications.php" class="MenuBarItemSubmenu">Publications</a>          
        <ul>
          <li><a href="2015o2019.php">2015-2019</a></li>
          <li><a href="2010o2014.php">2010-2014</a></li>
          <li><a href="2005o2009.php">2005-2009</a></li>
          <li><a href="2000o2004.php">2000-2004</a></li>
          <li><a href="1995o1999.php">1995-1999</a></li>
          <li><a href="1990o1994.php">1990-1994</a></li>
          <li><a href="o1990.php">Before 1990</a></li>
        </ul>
    <li><a href="../aboutUs.php">About Us</a>  </li>
    <li><a href="../contact.php">Contact Us</a></li>
    </ul>
    <div class="clear"></div></nav><!-- #EndLibraryItem --></nav></div>
  <div id="middle">
    <div id="mainsub"><!-- InstanceBeginEditable name="crumbs" --><script>breadcrumb()</script><!-- InstanceEndEditable -->
     
     
     
    <div class="clear"></div>
    
    
   <!-- InstanceBeginEditable name="main_content_center" -->
      <p class="header">Publications: 2010-2014</p>
      <p>&nbsp;</p>
      <A NAME="2014"></A>
      <p class="sub_ctrXS">2014</p>
      
      
     KA James KA,  GM Verkhivker. <a href="http://www.ploscompbiol.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pcbi.1003679&representation=PDF"> Structure-based network analysis of activation mechanisms in the ErbB family of receptor tyrosine kinases: the regulatory spine residues are global mediators of structural stability and allosteric interactions. </a> PLoS  One. 2014 Nov26;9(11):3113488. doi:10.1371/journal.pone.0113488. eCollection 2014. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Computational+Modeling+of+Allosteric+Regulation+in+the+Hsp90+Chaperones%3A+A+Statistical+Ensemble+Analysis+of+Protein+Structure+Networks+and+Allosteric+Communications."> PUBMED. </a><a href="#abstractStructBase" id="btn11"> Abstract. </a><br><br>
     
     <a_abstract NAME="abstractStructBase" id="x11"> ABSTRACT: A fundamental role of the Hsp90 chaperone in regulating functional activity of diverse protein clients is essential for the integrity of signaling networks. In this work we have combined biophysical simulations of the Hsp90 crystal structures with the protein structure network analysis to characterize the statistical ensemble of allosteric interaction networks and communication pathways in the Hsp90 chaperones. We have found that principal structurally stable communities could be preserved during dynamic changes in the conformational ensemble. The dominant contribution of the inter-domain rigidity to the interaction networks has emerged as a common factor responsible for the thermodynamic stability of the active chaperone form during the ATPase cycle. Structural stability analysis using force constant profiling of the inter-residue fluctuation distances has identified a network of conserved structurally rigid residues that could serve as global mediating sites of allosteric communication. Mapping of the conformational landscape with the network centrality parameters has demonstrated that stable communities and mediating residues may act concertedly with the shifts in the conformational equilibrium and could describe the majority of functionally significant chaperone residues. The network analysis has revealed a relationship between structural stability, global centrality and functional significance of hotspot residues involved in chaperone regulation. We have found that allosteric interactions in the Hsp90 chaperone may be mediated by modules of structurally stable residues that display high betweenness in the global interaction network. The results of this study have suggested that allosteric interactions in the Hsp90 chaperone may operate via a mechanism that combines rapid and efficient communication by a single optimal pathway of structurally rigid residues and more robust signal transmission using an ensemble of suboptimal multiple communication routes. This may be a universal requirement encoded in protein structures to balance the inherent tension between resilience and efficiency of the residue interaction networks.<br><br></a_abstract>
     
     
    GM. Verkhivker. <a href="http://onlinelibrary.wiley.com/doi/10.1002/ijch.201300143/pdf"> Computational Studies of Allosteric Regulation in the Hsp90 Molecular Chaperone: From Functional Dynamics and Protein Structure Networks to Allosteric Communications and Targeted Anti-Cancer Modulators.</a> Israel Journal of Chemistry. Special Issue: Computational Molecular Biophysics Volume 54, Issue 8-9, pages 1052–1064, August 2014.<a href="#abstractCompStudies" id="btn12"> Abstract. </a><br><br>
     
     <a_abstract NAME="abstractCompStudies" id="x12"> ABSTRACT: Computational studies of allosteric interactions have witnessed a recent renaissance fueled by growing inter- est in the modeling of complex molecular assemblies and biological networks. Allosteric interactions of the molecular chaperone Hsp90 with a diverse array of cochaperones and client proteins allow for molecular communication in signal transduction networks. In this review, recent developments in the understanding of allosteric interactions in the context of structural, functional, and computational studies of the Hsp90 chaperone are discussed. A comprehensive analysis of structural and network-based models of protein allostery is provided. Computational and experimental approaches and advances in the understanding of Hsp90 interactions and regulatory mechanisms are reviewed to provide a sys- tematic and critical view of the current progress and most challenging questions in the field. The current status and future prospects for translational research, bridging the basic science of chaperones with the discovery of anti- cancer therapies, are also highlighted.<br><br></a_abstract>
    
    
	  K. Blacklock, G. Verkhivker. <a href="http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003679"> Computational modeling of allosteric regulation in the hsp90 chaperones: a statistical ensemble analysis of protein structure networks and allosteric communications. </a> PLoS Comput Biol. 2014 Jun 12;10(6):e1003679. doi: 10.1371/journal.pcbi.1003679. eCollection 2014 Jun. <a href="https://www.ncbi.nlm.nih.gov/pubmed/?term=24922508"> PUBMED. </a> <a href="#abstractCompModel" id="btn13"> Abstract. </a><br><br> 
      
      <a_abstract NAME="abstractCompModel" id="x13"> ABSTRACT: A fundamental role of the Hsp90 chaperone in regulating functional activity of diverse protein clients is essential for the integrity of signaling networks. In this work we have combined biophysical simulations of the Hsp90 crystal structures with the protein structure network analysis to characterize the statistical ensemble of allosteric interaction networks and communication pathways in the Hsp90 chaperones. We have found that principal structurally stable communities could be preserved during dynamic changes in the conformational ensemble. The dominant contribution of the inter-domain rigidity to the interaction networks has emerged as a common factor responsible for the thermodynamic stability of the active chaperone form during the ATPase cycle. Structural stability analysis using force constant profiling of the inter-residue fluctuation distances has identified a network of conserved structurally rigid residues that could serve as global mediating sites of allosteric communication. Mapping of the conformational landscape with the network centrality parameters has demonstrated that stable communities and mediating residues may act concertedly with the shifts in the conformational equilibrium and could describe the majority of functionally significant chaperone residues. The network analysis has revealed a relationship between structural stability, global centrality and functional significance of hotspot residues involved in chaperone regulation. We have found that allosteric interactions in the Hsp90 chaperone may be mediated by modules of structurally stable residues that display high betweenness in the global interaction network. The results of this study have suggested that allosteric interactions in the Hsp90 chaperone may operate via a mechanism that combines rapid and efficient communication by a single optimal pathway of structurally rigid residues and more robust signal transmission using an ensemble of suboptimal multiple communication routes. This may be a universal requirement encoded in protein structures to balance the inherent tension between resilience and efficiency of the residue interaction networks.<br><br></a_abstract>
       
       
       A. Dixit, G. Verkhivker. <a href="http://www.plosone.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pone.0086547&representation=PDF">Structure-functional prediction and analysis of cancer mutation effects in protein kinases.</a> Comput Math Methods Med. 2014;2014:653487. doi: 10.1155/2014/653487. Epub 2014 Apr 8. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24817905"> PUBMED. </a> <a href="#abstractStructFunc" id="btn14"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractStructFunc" id="x14"> ABSTRACT: A central goal of cancer research is to discover and characterize the functional effects of mutated genes that contribute to tumorigenesis. In this study, we provide a detailed structural classification and analysis of functional dynamics for members of protein kinase families that are known to harbor cancer mutations. We also present a systematic computational analysis that combines sequence and structure-based prediction models to characterize the effect of cancer mutations in protein kinases. We focus on the differential effects of activating point mutations that increase protein kinase activity and kinase-inactivating mutations that decrease activity. Mapping of cancer mutations onto the conformational mobility profiles of known crystal structures demonstrated that activating mutations could reduce a steric barrier for the movement from the basal "low" activity state to the "active" state. According to our analysis, the mechanism of activating mutations reflects a combined effect of partial destabilization of the kinase in its inactive state and a concomitant stabilization of its active-like form, which is likely to drive tumorigenesis at some level. Ultimately, the analysis of the evolutionary and structural features of the major cancer-causing mutational hotspot in kinases can also aid in the correlation of kinase mutation effects with clinical outcomes. <br><br></a_abstract>
       
       K. Blacklock, G. Verkhivker. <a href="http://www.plosone.org/article/fetchObject.action?uri=info%3Adoi%2F10.1371%2Fjournal.pone.0086547&representation=PDF"> Allosteric regulation of the Hsp90 dynamics and stability by client recruiter cochaperones: protein structure network modeling. </a> PLoS One. 2014 Jan 20;9(1):e86547. doi: 10.1371/journal.pone.0086547. eCollection 2014. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24466147"> PUBMED. </a><a href="#abstractAlloReg" id="btn15"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractAlloReg" id="x15"> ABSTRACT: The fundamental role of the Hsp90 chaperone in supporting functional activity of diverse protein clients is anchored by specific cochaperones. A family of immune sensing client proteins is delivered to the Hsp90 system with the aid of cochaperones Sgt1 and Rar1 that act cooperatively with Hsp90 to form allosterically regulated dynamic complexes. In this work, functional dynamics and protein structure network modeling are combined to dissect molecular mechanisms of Hsp90 regulation by the client recruiter cochaperones. Dynamic signatures of the Hsp90-cochaperone complexes are manifested in differential modulation of the conformational mobility in the Hsp90 lid motif. Consistent with the experiments, we have determined that targeted reorganization of the lid dynamics is a unifying characteristic of the client recruiter cochaperones. Protein network analysis of the essential conformational space of the Hsp90-cochaperone motions has identified structurally stable interaction communities, interfacial hubs and key mediating residues of allosteric communication pathways that act concertedly with the shifts in conformational equilibrium. The results have shown that client recruiter cochaperones can orchestrate global changes in the dynamics and stability of the interaction networks that could enhance the ATPase activity and assist in the client recruitment. The network analysis has recapitulated a broad range of structural and mutagenesis experiments, particularly clarifying the elusive role of Rar1 as a regulator of the Hsp90 interactions and a stability enhancer of the Hsp90-cochaperone complexes. Small-world organization of the interaction networks in the Hsp90 regulatory complexes gives rise to a strong correspondence between highly connected local interfacial hubs, global mediator residues of allosteric interactions and key functional hot spots of the Hsp90 activity. We have found that cochaperone-induced conformational changes in Hsp90 may be determined by specific interaction networks that can inhibit or promote progression of the ATPase cycle and thus control the recruitment of client proteins.<br><br></a_abstract>
       <A NAME="2013"></A>
       <p class="sub_ctrXS">2013</p>
       
       
       Lawless N, Blacklock K, Berrigan E, Verkhivker G. <a href="http://www.mdpi.com/1424-8247/6/11/1407/pdf"> Structural bioinformatics and protein docking analysis of the molecular chaperone-kinase interactions: towards allosteric inhibition of protein kinases by targeting the hsp90-cdc37 chaperone machinery.</a> Pharmaceuticals (Basel). 2013 Nov 11;6(11):1407-28. doi: 10.3390/ph6111407. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24287464"> PUBMED. </a><a href="#abstractStructBio" id="btn16"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractStructBio" id="x16"> ABSTRACT: A fundamental role of the Hsp90-Cdc37 chaperone system in mediating maturation of protein kinase clients and supporting kinase functional activity is essential for the integrity and viability of signaling pathways involved in cell cycle control and organism development. Despite significant advances in understanding structure and function of molecular chaperones, the molecular mechanisms and guiding principles of kinase recruitment to the chaperone system are lacking quantitative characterization. Structural and thermodynamic characterization of Hsp90-Cdc37 binding with protein kinase clients by modern experimental techniques is highly challenging, owing to a transient nature of chaperone-mediated interactions. In this work, we used experimentally-guided protein docking to probe the allosteric nature of the Hsp90-Cdc37 binding with the cyclin-dependent kinase 4 (Cdk4) kinase clients. The results of docking simulations suggest that the kinase recognition and recruitment to the chaperone system may be primarily determined by Cdc37 targeting of the N-terminal kinase lobe. The interactions of Hsp90 with the C-terminal kinase lobe may provide additional "molecular brakes" that can lock (or unlock) kinase from the system during client loading (release) stages. The results of this study support a central role of the Cdc37 chaperone in recognition and recruitment of the kinase clients. Structural analysis may have useful implications in developing strategies for allosteric inhibition of protein kinases by targeting the Hsp90-Cdc37 chaperone machinery. <br><br></a_abstract>
       
       Blacklock K, Verkhivker GM. <a href="http://www.medscape.com/medline/abstract/24191708"> Experimentally guided structural modeling and dynamics analysis of Hsp90-p53 interactions: allosteric regulation of the Hsp90 chaperone by a client protein.</a> J Chem Inf Model. 2013 Nov 25;53(11):2962-78. doi: 10.1021/ci400434g. Epub 2013 Nov 12.<a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=24191708"> PUBMED. </a><a href="#abstractExpGuide" id="btn17"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractExpGuide" id="x17"> ABSTRACT: A fundamental role of the Hsp90 chaperone system in mediating maturation of protein clients is essential for the integrity of signaling pathways involved in cell cycle control and organism development. Molecular characterization of Hsp90 interactions with client proteins is fundamental to understanding the activity of many tumor-inducing signaling proteins and presents an active area of structural and biochemical studies. In this work, we have probed mechanistic aspects of allosteric regulation of Hsp90 by client proteins via a detailed computational study of Hsp90 interactions with the tumor suppressor protein p53. Experimentally guided protein docking and molecular dynamics structural refinement have reconstructed the recognition-competent states of the Hsp90-p53 complexes that are consistent with the NMR studies. Protein structure network analysis has identified critical interacting networks and specific residues responsible for structural integrity and stability of the Hsp90-p53 complexes. Coarse-grained modeling was used to characterize the global dynamics of the regulatory complexes and map p53-induced changes in the conformational equilibrium of Hsp90. The variations in the functional dynamics profiles of the Hsp90-p53 complexes are consistent with the NMR studies and could explain differences in the functional role of the alternative binding sites. Despite the overall similarity of the collective movements and the same global interaction footprint, p53 binding at the C-terminal interaction site of Hsp90 may have a more significant impact on the chaperone dynamics, which is consistent with the stronger allosteric effect of these interactions revealed by the experimental studies. The results suggest that p53-induced modulation of the global dynamics and structurally stable interaction networks can target the regulatory hinge regions and facilitate stabilization of the closed Hsp90 dimer that underlies the fundamental stimulatory effect of the p53 client. <br><br></a_abstract>
      
       
    Blacklock K, Verkhivker GM.<a href="http://www.researchgate.net/profile/Kristin_Blacklock/publication/256102740_Differential_Modulation_of_Functional_Dynamics_and_Allosteric_Interactions_in_the_Hsp90-Cochaperone_Complexes_with_p23_and_Aha1_A_Computational_Study/links/00b495255acc861427000000?ev=pub_ext_doc_dl&origin=publication_detail&inViewer=true"> Differential modulation of functional dynamics and allosteric interactions in the Hsp90-cochaperone complexes with p23 and Aha1: a computational study.</a> PLoS One. 2013 Aug 19;8(8):e71936. doi: 10.1371/journal.pone.0071936. eCollection 2013. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=23977182"> PUBMED. </a><a href="#abstractDiffModul" id="btn18"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractDiffModul" id="x18"> ABSTRACT: Allosteric interactions of the molecular chaperone Hsp90 with a large cohort of cochaperones and client proteins allow for molecular communication and event coupling in signal transduction networks. The integration of cochaperones into the Hsp90 system is driven by the regulatory mechanisms that modulate the progression of the ATPase cycle and control the recruitment of the Hsp90 clientele. In this work, we report the results of computational modeling of allosteric regulation in the Hsp90 complexes with the cochaperones p23 and Aha1. By integrating protein docking, biophysical simulations, modeling of allosteric communications, protein structure network analysis and the energy landscape theory we have investigated dynamics and stability of the Hsp90-p23 and Hsp90-Aha1 interactions in direct comparison with the extensive body of structural and functional experiments. The results have revealed that functional dynamics and allosteric interactions of Hsp90 can be selectively modulated by these cochaperones via specific targeting of the regulatory hinge regions that could restrict collective motions and stabilize specific chaperone conformations. The protein structure network parameters have quantified the effects of cochaperones on conformational stability of the Hsp90 complexes and identified dynamically stable communities of residues that can contribute to the strengthening of allosteric interactions. According to our results, p23-mediated changes in the Hsp90 interactions may provide "molecular brakes" that could slow down an efficient transmission of the inter-domain allosteric signals, consistent with the functional role of p23 in partially inhibiting the ATPase cycle. Unlike p23, Aha1-mediated acceleration of the Hsp90-ATPase cycle may be achieved via modulation of the equilibrium motions that facilitate allosteric changes favoring a closed dimerized form of Hsp90. The results of our study have shown that Aha1 and p23 can modulate the Hsp90-ATPase activity and direct the chaperone cycle by exerting the precise control over structural stability, global movements and allosteric communications in Hsp90.<br><br></a_abstract>
     
        <A NAME="2012"></A> 
         <p class="sub_ctrXS">2012</p>
         
           
      Dixit A, Verkhivker GM.<a href="http://www.medscape.com/medline/abstract/22992037"> Integrating ligand-based and protein-centric virtual screening of kinase inhibitors using ensembles of multiple protein kinase genes and conformations. </a> J Chem Inf Model. 2012 Oct 22;52(10):2501-15. doi: 10.1021/ci3002638. Epub 2012 Oct 1. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=22992037"> PUBMED. </a><a href="#abstractIntLig" id="btn19"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractIntLig" id="x19"> ABSTRACT: The rapidly growing wealth of structural and functional information about kinase genes and kinase inhibitors that is fueled by a significant therapeutic role of this protein family provides a significant impetus for development of targeted computational screening approaches. In this work, we explore an ensemble-based, protein-centric approach that allows for simultaneous virtual ligand screening against multiple kinase genes and multiple kinase receptor conformations. We systematically analyze and compare the results of ligand-based and protein-centric screening approaches using both single-receptor and ensemble-based docking protocols. A panel of protein kinase targets that includes ABL, EGFR, P38, CDK2, TK, and VEGFR2 kinases is used in this comparative analysis. By applying various performance metrics we have shown that ligand-centric shape matching can provide an effective enrichment of active compounds outperforming single-receptor docking screening. However, ligand-based approaches can be highly sensitive to the choice of inhibitor queries. Employment of multiple inhibitor queries combined with parallel selection ranking criteria can improve the performance and efficiency of ligand-based virtual screening. We also demonstrated that replica-exchange Monte Carlo docking with kinome-based ensembles of multiple crystal structures can provide a superior early enrichment on the kinase targets. The central finding of this study is that incorporation of the template-based structural information about kinase inhibitors and protein kinase structures in diverse functional states can significantly enhance the overall performance and robustness of both ligand and protein-centric screening strategies. The results of this study may be useful in virtual screening of kinase inhibitors potentially offering a beneficial spectrum of therapeutic activities across multiple disease states. <br><br></a_abstract>
     
       
        G Verkhivker. <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3397965/pdf/pone.0040897.pdf">Simulating Molecular Mechanisms of the MDM2-Mediated Regulatory Interactions: A Conformational Selection Model of the MDM2 Lid Dynamics.</a> Plos One 2012;7(7):e40897. Epub 2012 Jul 16.<a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Simulating+Molecular+Mechanisms+of+the+MDM2-Mediated+Regulatory+Interactions%3A+A+Conformational+Selection+Model+of+the+MDM2+Lid+Dynamics."> PUBMED. </a><a href="#abstractSimulating" id="btn20"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractSimulating" id="x20"> ABSTRACT: Diversity and complexity of MDM2 mechanisms govern its principal function as the cellular antagonist of the p53 tumor suppressor. Structural and biophysical studies have demonstrated that MDM2 binding could be regulated by the dynamics of a pseudo-substrate lid motif. However, these experiments and subsequent computational studies have produced conflicting mechanistic models of MDM2 function and dynamics. We propose a unifying conformational selection model that can reconcile experimental findings and reveal a fundamental role of the lid as a dynamic regulator of MDM2-mediated binding. In this work, structure, dynamics and energetics of apo-MDM2 are studied as a function of posttranslational modifications and length of the lid. We found that the dynamic equilibrium between ‘‘closed’’ and ‘‘semi-closed’’ lid forms may be a fundamental characteristic of MDM2 regulatory interactions, which can be modulated by phosphorylation, phosphomimetic mutation as well as by the lid size. Our results revealed that these factors may regulate p53-MDM2 binding by fine-tuning the thermodynamic equilibrium between preexisting conformational states of apo-MDM2. In agreement with NMR studies, the effect of phosphorylation on MDM2 interactions was more pronounced with the truncated lid variant that favored the thermodynamically dominant closed form. The phosphomimetic mutation S17D may alter the lid dynamics by shifting the thermodynamic equilibrium towards the ensemble of ‘‘semi-closed’’ conformations. The dominant ‘‘semi- closed’’ lid form and weakened dependence on the phosphorylation seen in simulations with the complete lid can provide a rationale for binding of small p53-based mimetics and inhibitors without a direct competition with the lid dynamics. The results suggested that a conformational selection model of preexisting MDM2 states may provide a robust theoretical framework for understanding MDM2 dynamics. Probing biological functions and mechanisms of MDM2 regulation would require further integration of computational and experimental studies and may help to guide drug design of novel anti- cancer therapeutics. <br><br></a_abstract>
        
        
      A. Dixit, G.Verkhivker.<a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3356286/pdf/pone.0037605.pdf"> Probing molecular mechanisms of the hsp90 chaperone: biophysical modeling identifies key regulators of functional dynamics.</a> PLoS One. 2012;7(5):e37605. Epub 2012 May 18.<a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Probing+Molecular+Mechanisms+of+the+Hsp90+Chaperone%3A+Biophysical+Modeling+Identifies+Key+Regulators+of+Functional+Dynamics">  PUBMED. </a><a href="#abstractProbing" id="btn21"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractProbing" id="x21"> ABSTRACT: Deciphering functional mechanisms of the Hsp90 chaperone machinery is an important objective in cancer biology aiming to facilitate discovery of targeted anti-cancer therapies. Despite significant advances in understanding structure and function of molecular chaperones, organizing molecular principles that control the relationship between conformational diversity and functional mechanisms of the Hsp90 activity lack a sufficient quantitative characterization. We combined molecular dynamics simulations, principal component analysis, the energy landscape model and structure-functional analysis of Hsp90 regulatory interactions to systematically investigate functional dynamics of the molecular chaperone. This approach has identified a network of conserved regions common to the Hsp90 chaperones that could play a universal role in coordinating functional dynamics, principal collective motions and allosteric signaling of Hsp90. We have found that these functional motifs may be utilized by the molecular chaperone machinery to act collectively as central regulators of Hsp90 dynamics and activity, including the inter-domain communications, control of ATP hydrolysis, and protein client binding. These findings have provided support to a long-standing assertion that allosteric regulation and catalysis may have emerged via common evolutionary routes. The interaction networks regulating functional motions of Hsp90 may be determined by the inherent structural architecture of the molecular chaperone. At the same time, the thermodynamics- based ‘‘conformational selection’’ of functional states is likely to be activated based on the nature of the binding partner. This mechanistic model of Hsp90 dynamics and function is consistent with the notion that allosteric networks orchestrating cooperative protein motions can be formed by evolutionary conserved and sparsely connected residue clusters. Hence, allosteric signaling through a small network of distantly connected residue clusters may be a rather general functional requirement encoded across molecular chaperones. The obtained insights may be useful in guiding discovery of allosteric Hsp90 inhibitors targeting protein interfaces with co-chaperones and protein binding clients. <br><br></a_abstract>
      
      <A NAME="2011"></A> 
      <p class="sub_ctrXS">2010 - 2011</p>
      
      
      
     A. Dixit, AG. Verkhivker.<a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3188581/pdf/pone.0026071.pdf">The energy landscape analysis of cancer mutations in protein kinases.</a> PLoS One. 2011;6(10):e26071. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=The+Energy+Landscape+Analysis+of+Cancer+Mutations+in+Protein+Kinases">PUBMED. </a><a href="#abstractEnergy" id="btn22"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractEnergy" id="x22"> ABSTRACT: The growing interest in quantifying the molecular basis of protein kinase activation and allosteric regulation by cancer mutations has fueled computational studies of allosteric signaling in protein kinases. In the present study, we combined computer simulations and the energy landscape analysis of protein kinases to characterize the interplay between oncogenic mutations and locally frustrated sites as important catalysts of allostetric kinase activation. While structurally rigid kinase core constitutes a minimally frustrated hub of the catalytic domain, locally frustrated residue clusters, whose interaction networks are not energetically optimized, are prone to dynamic modulation and could enable allosteric conformational transitions. The results of this study have shown that the energy landscape effect of oncogenic mutations may be allosteric eliciting global changes in the spatial distribution of highly frustrated residues. We have found that mutation-induced allosteric signaling may involve a dynamic coupling between structurally rigid (minimally frustrated) and plastic (locally frustrated) clusters of residues. The presented study has demonstrated that activation cancer mutations may affect the thermodynamic equilibrium between kinase states by allosterically altering the distribution of locally frustrated sites and increasing the local frustration in the inactive form, while eliminating locally frustrated sites and restoring structural rigidity of the active form. The energy landsape analysis of protein kinases and the proposed role of locally frustrated sites in activation mechanisms may have useful implications for bioinformatics-based screening and detection of functional sites critical for allosteric regulation in complex biomolecular systems.<br><br></a_abstract>
     
      A. Dixit, , G. Verkhivker.<a href="http://www.ploscompbiol.org/article/fetchObject.action?uri=info%3Adoi%2F10.1371%2Fjournal.pcbi.1002179&representation=PDF"> Computational Modeling of Allosteric Communication Reveals Organizing Principles of Mutation-Induced Signaling in ABL and EGFR Kinases.</a> PLoS Comput Biol. 2011 Oct;7(10):e1002179. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Computational+Modeling+of+Allosteric+Communication+Reveals+Organizing+Principles+of+Mutation-Induced+Signaling+in+ABL+and+EGFR+Kinases.">PUBMED. </a><a href="#abstractModelAllo" id="btn23"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractModelAllo" id="x23"> ABSTRACT: The emerging structural information about allosteric kinase complexes and the growing number of allosteric inhibitors call for a systematic strategy to delineate and classify mechanisms of allosteric regulation and long-range communication that control kinase activity. In this work, we have investigated mechanistic aspects of long-range communications in ABL and EGFR kinases based on the results of multiscale simulations of regulatory complexes and computational modeling of signal propagation in proteins. These approaches have been systematically employed to elucidate organizing molecular principles of allosteric signaling in the ABL and EGFR multi-domain regulatory complexes and analyze allosteric signatures of the gate- keeper cancer mutations. We have presented evidence that mechanisms of allosteric activation may have universally evolved in the ABL and EGFR regulatory complexes as a product of a functional cross-talk between the organizing aF-helix and conformationally adaptive aI-helix and aC-helix. These structural elements form a dynamic network of efficiently communicated clusters that may control the long-range interdomain coupling and allosteric activation. The results of this study have unveiled a unifying effect of the gate-keeper cancer mutations as catalysts of kinase activation, leading to the enhanced long-range communication among allosterically coupled segments and stabilization of the active kinase form. The results of this study can reconcile recent experimental studies of allosteric inhibition and long-range cooperativity between binding sites in protein kinases. The presented study offers a novel molecular insight into mechanistic aspects of allosteric kinase signaling and provides a quantitative picture of activation mechanisms in protein kinases at the atomic level.<br><br></a_abstract>
      
      
     R. L. Matts, A. Dixit, L.B. Peterson, L. Sun, S. Voruganti, . Kalyanaraman, S. D. Hartson, G. M. Verkhivker, B. S. J. Blagg.<a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3164513/pdf/nihms-295676.pdf"> Elucidation and assessment of the Hsp90 C-terminal inhibitor binding site. </a> ACS Chem Biol. 2011 Aug 19;6(8):800-807. <a href="http://www.ncbi.nlm.nih.gov/pubmed/21548602">PUBMED. </a><a href="#abstractElucid" id="btn24"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractElucid" id="x24"> ABSTRACT: The Hsp90 chaperone machine is required for the folding, activation, and/or stabilization of more than 50 proteins directly related to malignant progression. Hsp90 contains small molecule binding sites at both its N- and C-terminal domains; however, limited structural and biochemical data regarding the C-terminal binding site is available. In this report, the small molecule binding site in the Hsp90 C-terminal domain was revealed by protease fingerprinting and photoaffinity labeling utilizing LC-MS/MS. The identified site was characterized by generation of a homology model for hHsp90α using the SAXS open structure of HtpG and docking the bioactive conformation of NB into the generated model. The resulting model for the bioactive conformation of NB bound to Hsp90α is presented herein.<br><br></a_abstract>
     
     
    R. L. Matts, G. E. L. Brandt, Y. Lu, A. Dixit, M. Mollapour, S. Wang, A. C. Donnelly, L. Neckers, G.M.Verkhivker, B. S. J. Blagg. <a href="http://www.sciencedirect.com/science/article/pii/S0968089610009521">A systematic protocol for the characterization of Hsp90 modulators.</a> Bioorg Med Chem. 2011 19(1):684-92. <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term=A+systematic+protocol+for+the+characterization+of+Hsp90+modulators.">PUBMED. </a><a href="#abstractProtocol" id="btn25"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractProtocol" id="x25"> ABSTRACT: Several Hsp90 modulators have been identified including the N-terminal ligand geldanamycin (GDA), the C-terminal ligand novobiocin (NB), and the co-chaperone disruptor celastrol. Other Hsp90 modulators elicit a mechanism of action that remains unknown. For example, the natural product gedunin and the synthetic anti-spermatogenic agent H2-gamendazole, recently identified Hsp90 modulators, manifest biological activity through undefined mechanisms. Herein, we report a series of biochemical techniques used to classify such modulators into identifiable categories. Such studies provided evidence that gedunin and H2-gamendazole both modulate Hsp90 via a mechanism similar to celastrol, and unlike NB or GDA.<br><br></a_abstract>
     
     
      A. Friedman, A. Torkamani, G.M. Verkhivker, N.J. Schork. From coding variants to structure and function insights. In the book “Protein Structure” Ed.Lauren M. Haggerty  Series:   Protein Science and Engineering Nova Science Publishers, 2011.<a href="#abstractCoding" id="btn26"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractCoding" id="x26"> ABSTRACT: The availability of cost-effective DNA sequencing technologies has led to the identification and cataloguing of millions of naturally occurring inherited and somatic human genomic variations. As a result, questions concerning the ultimate phenotypic and functional significance of these variations have been raised. Although some large-scale initiatives have been launched for this purpose, including the Encyclopedia of DNA Elements (ENCODE) initiative, there is a need for the DNA sequencing and genomics communities to reach out and foster greater collaborative opportunities with the functional genomics community. One area that is ripe for this kind of activity is the functional characterization of coding variations, as structural proteomics and crystallography researchers may both benefit from, and contribute to, an understanding of the molecular and phenotypic influence of such variations. We briefly review the motivation for this kind of interaction and draw on publicly available data to showcase its need. We also consider how relevant research could be pursued.<br><br></a_abstract>
      
      G. Morra, M. A. C. Neves, C. J. Plescia, S. Tsustsumi, L. Neckers, G.M. Verkhivker, D. C. Altieri, G. Colombo. <a href="http://pubs.acs.org/doi/abs/10.1021/ct100334n"> Dynamics-Based Discovery of Allosteric Inhibitors: Selection of New Ligands for the C-terminal Domain of Hsp90.</a> J. Chem. Theory Comput., 6 : 2978–2989, 2010. <a href="https://www.ncbi.nlm.nih.gov/pubmed/?term=Dynamics-Based+Discovery+of+Allosteric+Inhibitors%3A+Selection+of+New+Ligands+for+the+C-terminal+Domain+of+Hsp90"> PUBMED. </a> <a href="#abstractDynamicDisc" id="btn27"> Abstract. </a><br><br> 
       
       <a_abstract NAME="abstractDynamicDisc" id="x27"> ABSTRACT: The study of allosteric functional modulation in dynamic proteins is attracting increasing attention. In particular, the discovery of new allosteric sites may generate novel opportunities and strategies for drug development, overcoming the limits of classical active-site oriented drug design. In this paper, we report on the results of a novel, ab initio, fully computational approach for the discovery of allosteric inhibitors based on the physical characterization of signal propagation mechanisms in proteins and apply it to the important molecular chaperone Hsp90. We first characterize the allosteric “hot spots” involved in interdomain communication pathways from the nucleotide-binding site in the N-domain to the distal C-domain. On this basis, we develop dynamic pharmacophore models to screen drug libraries in the search for small molecules with the functional and conformational properties necessary to bind these “hot spot” allosteric sites. Experimental tests show that the selected moelcules bind the Hsp90 C-domain, exhibit antiproliferative activity in different tumor cell lines, while not affecting proliferation of normal human cells, destabilize Hsp90 client proteins, and disrupt association with several cochaperones known to bind the N- and M-domains of Hsp90. These results prove that the hits alter Hsp90 function by affecting its conformational dynamics and recognition properties through an allosteric mechanism. These findings provide us with new insights on the discovery and development of new allosteric inhibitors that are active on important cellular pathways through computational biology. Though based on the specific case of Hsp90, our approach is general and can readily be extended to other target proteins and pathways.<br><br></a_abstract>
       
       
     <p class="sub_ctrXS">More Publications</p> 
     
     <a href="/Publications/2015o2019.php">2015 - 2019 (14 Publications)</a><br>
     <a href="/Publications/2005o2009.php">2005 - 2009 (26 Publications) </a><br>
     <a href="/Publications/2000o2004.php">2000 - 2004 (17 Publications) </a><br>
     <a href="/Publications/1995o1999.php">1995 - 1999 (21 Publications) </a><br>
     <a href="/Publications/1990o1994.php">1990 - 1994 (9 Publications)</a><br>
     <a href="/Publications/o1990.php">Before 1990     (15 Publications) </a><br><br>
      <!-- InstanceEndEditable -->
      <div class="clear"></div>
    
    
    
    </div>
  </div>
  <footer >
    <div id="bottom">
      <div class="clear"></div>
    </div>
  </footer> <div id="subfooter">©2016 Chapman University • One University Drive, Orange, CA 92866 • Phone: (714) 997-6815</div>
</div>
</body>
<!-- InstanceEnd --></html>